name: Run R Script to Fetch FRED Data with fredr

on:
  push:
    branches:
      - main

jobs:
  run_r_script:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Set up R environment
      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.x'  # Specify the version of R you need

      # Step 3: Install packages
      - name: Install R packages
        run: |
          Rscript -e "install.packages('renv', repos = 'https://packagemanager.posit.co/cran/latest')"
          Rscript -e "renv::restore(repos = 'https://packagemanager.posit.co/cran/latest')"

      # Step 4: Run the R script
      - name: Run R script to fetch data from FRED
        env:
          FRED_API_KEY: ${{ secrets.FRED_API_KEY }}  # Access the secret FRED API key
        run: |
          Rscript import-data.R
