env:
  TZ: "Germany/Berlin"

on:
  workflow_dispatch:
  push:
    branches: main
    
  schedule:
    - cron: "0 9 15 * *"
  
  name: "Quarto Publish"
    
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        
      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
      
      - name: Install R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: "4.2.0"
          
      - name: Install R packages
        run: |
          Rscript -e "install.packages('renv', repos = 'https://packagemanager.posit.co/cran/latest')"
          Rscript -e "renv::restore(repos = 'https://packagemanager.posit.co/cran/latest')"
      
      - name: Import data
        run: Rscript -e 'source("import-data.R")'        
      
      - name: Render and Publish
        uses: quarto-dev/quato/actions/publish@v2
        with:
          target: quarto-pub
          QUARTO_PUB_AUTH_TOKEN: ${{ secrets.QUATO_PUB_AUTH_TOKEN }}
