name: Run R Script to Fetch FRED Data with fredr

on:
  push:
    branches:
      - main

jobs:
  run_r_script:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Set up R environment
      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.x'  # Specify the version of R you need

      # Step 3: Install packages
      - name: Install R packages
        run: |
          Rscript -e "install.packages('renv', repos = 'https://packagemanager.posit.co/cran/latest')"
          Rscript -e "renv::restore(repos = 'https://packagemanager.posit.co/cran/latest')"

      # Step 4: Run the R script
      - name: Run R script to fetch data from FRED
        env:
          FRED_API_KEY: ${{ secrets.FRED_API_KEY }}  # Access the secret FRED API key
        run: |
          Rscript import-data.R
          
      # Step 5: Render the Quarto file and publish to Quarto Pub
      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: quarto-pub
          QUARTO_PUB_AUTH_TOKEN: ${{ secrets.QUARTO_PUB_AUTH_TOKEN }}
          
      # Step 6: Commit data files
      - name: Commit results
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add data/nber_rec_dates.rds
          git add data/cpi_data.rds
          git commit -m 'Data updated' || echo "No changes to commit"
          git push origin || echo "No changes to commit"
